In [1]:
import pandas as pd
import numpy as np

In [2]:
movie_df = pd.read_excel("movie.xlsx")
movie_df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.130,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.460,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.120,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.320,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.020,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,47.985,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.540,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.010,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,47.985,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.640,11.0

In [7]:
movie_df['Genre'] = movie_df['Genre'].str.replace(',', ', ', regex=False)

In [8]:
genre_cols = movie_df['Genre'].str.get_dummies(sep=', ')
movie_df = pd.concat([movie_df, genre_cols], axis=1)

In [9]:
genre_cols.columns.tolist()

['Action',
 'Adventure',
 'Animation',
 'Biography',
 'Comedy',
 'Crime',
 'Drama',
 'Family',
 'Fantasy',
 'History',
 'Horror',
 'Music',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Sport',
 'Thriller',
 'War',
 'Western']

In [10]:
movie_df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,...,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
0,1,Guardians of the Galaxy,"Action, Adventure, Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,...,0,0,0,0,0,1,0,0,0,0
1,2,Prometheus,"Adventure, Mystery, Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,...,0,0,0,1,0,1,0,0,0,0
2,3,Split,"Horror, Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,...,1,0,0,0,0,0,0,1,0,0
3,4,Sing,"Animation, Comedy, Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,...,0,0,0,0,0,0,0,0,0,0
4,5,Suicide Squad,"Action, Adventure, Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime, Drama, Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,...,0,0,0,1,0,0,0,0,0,0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,...,1,0,0,0,0,0,0,0,0,0
997,998,Step Up 2: The Streets,"Drama, Music, Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,...,0,1,0,0,1,0,0,0,0,0
998,999,Search Party,"Adventure, Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,...,0,0,0,0,0,0,0,0,0,0
999,1000,Nine Lives,"Comedy, Family, Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,...,0,0,0,0,0,0,0,0,0,0

In [11]:
movie_df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Action', 'Adventure', 'Animation', 'Biography', 'Comedy',
       'Crime', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [25]:
movies_df = movie_df[[
    'Title',
    'Year',
    'Rating',
    'Votes',
    'Runtime (Minutes)',
    'Revenue (Millions)',
    'Metascore',
    'Director'
]].copy()

In [26]:
movies_df.to_csv('movies_main.csv', index=False)

In [19]:
genre_df = movie_df[['Title', 'Genre', 'Rating', 'Revenue (Millions)', 'Metascore']].copy()
genre_df['Genre'] = genre_df['Genre'].str.split(', ')
genre_df = genre_df.explode('Genre')

In [20]:
genre_df

                       Title      Genre  Rating  Revenue (Millions)  Metascore
0    Guardians of the Galaxy     Action     8.1             333.130       76.0
0    Guardians of the Galaxy  Adventure     8.1             333.130       76.0
0    Guardians of the Galaxy     Sci-Fi     8.1             333.130       76.0
1                 Prometheus  Adventure     7.0             126.460       65.0
1                 Prometheus    Mystery     7.0             126.460       65.0
..                       ...        ...     ...                 ...        ...
998             Search Party  Adventure     5.6              47.985       22.0
998             Search Party     Comedy     5.6              47.985       22.0
999               Nine Lives     Comedy     5.3              19.640       11.0
999               Nine Lives     Family     5.3              19.640       11.0
999               Nine Lives    Fantasy     5.3              19.640       11.0

[2555 rows x 5 columns]

In [21]:
actors_df = movie_df[['Title', 'Actors']].copy()
actors_df['Actors'] = actors_df['Actors'].str.split(', ')
actors_df = actors_df.explode('Actors')
actors_df

                       Title                               Actors
0    Guardians of the Galaxy                          Chris Pratt
0    Guardians of the Galaxy                           Vin Diesel
0    Guardians of the Galaxy                       Bradley Cooper
0    Guardians of the Galaxy                          Zoe Saldana
1                 Prometheus                         Noomi Rapace
..                       ...                                  ...
998             Search Party                          T.J. Miller
998             Search Party  Thomas Middleditch,Shannon Woodward
999               Nine Lives                         Kevin Spacey
999               Nine Lives                      Jennifer Garner
999               Nine Lives            Robbie Amell,Cheryl Hines

[3650 rows x 2 columns]

In [22]:
genre_df.to_csv('movies_genre.csv', index=False)

In [23]:
actors_df.to_csv('movies_actors.csv', index=False)

In [3]:
movie_df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [5]:
movie_df["Revenue (Millions)"]

0      333.130
1      126.460
2      138.120
3      270.320
4      325.020
        ...
995     47.985
996     17.540
997     58.010
998     47.985
999     19.640
Name: Revenue (Millions), Length: 1000, dtype: float64